### ISSUE TITLE
cant even start a run with ONLY epiphany on my main file

### ISSUE THREAD

**Issue by avkoleroff** [OpenSauce04/EpiphanyIssues#107]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I have checked that I am running the latest version of Epiphany
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing either the 'Mod Error Container' mod or Repentogon before filing this issue

### What Happened?

all was sayed in the title
on second file it working normally

### Screenshots

https://github.com/user-attachments/assets/901aa0fe-41e1-4035-9b7e-32f352cdedfa

### Steps to Reproduce the Issue

i dont tf know

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/user-attachments/files/16202922/EpiphanyDiagnostics.tar.gz)

### Additional Context

it was normal, previosly i wanted to unlock tr isaac, went to sleep, and then ANY run with epiphany broking isaac :sob:
P. S. sorry for bad english

**Comment by avkoleroff** [comment]
I also tried reinstall isaac, nothing changed

**Comment by avkoleroff** [comment]
I deleted epiphany save file by myself and it fixed da problem
wipe-save from debug console didnt help btw

**Comment by DannyElisha** [comment]
Sorry to bump this, could you list where you've found the epiphany save file?
I legit scoured my PC and have not found anything; my problem persists pretty much like yours only on main save

**Comment by avkoleroff** [comment]
> Sorry to bump this, could you list where you've found the epiphany save file? I legit scoured my PC and have not found anything; my problem persists pretty much like yours only on main save
here you go!
your disk > program files (x86) > Steam > useradata > open pack you see > 250900 (yeah, those numbers) > remote 
there you can delete / insert your data
