### ISSUE TITLE
K.A.E.K. Not Spawning

### ISSUE THREAD

**Issue by ShanePatSmith** [OpenSauce04/EpiphanyIssues#11]
**Describe the bug**
---
I'm working on unlocking Tarnished Keepers but the K.A.E.K. isn't spawning in any of the secret rooms. It spawned one time, and then never again in any subsequent runs.

[modlist.txt](https://github.com/OpenSauce04/Epiphany/files/9804631/modlist.txt)

**Version information:**
---
 - Installed wave number: Wave 4
 - Version number: 4.3

**Comment by OpenSauce04** [comment]
This is a confirmed compatability issue with another mod

**Comment by Kilvar** [comment]
In addition to K.A.E.K not spawning, i noticed that when getting this bug, the dad's wallet passive effect from it is permanently active not just for greed mode, but every other normal run as any character as well. This happens even after unlocking TR Keeper

**Comment by OpenSauce04** [comment]
If this issue is still occurring, please post a new issue report with updated information and logs
