### ISSUE TITLE
Using the joker card in the broken halo devil room creates a softlock

### ISSUE THREAD

**Issue by Mat12999** [OpenSauce04/EpiphanyIssues#20]
**Describe the bug**
---
I was playing tarnished judas with the item broken halo and the joker card, when i visited the devil room from broken halo i decided yo use the joker right there, but when i tried to leave the devil room it just put me right back in it, i tried closing the game to fix this but the game crashed, and everytime i tried to enter the run it just crashed

**To Reproduce**
---
Use the joker card on the devil room of broken halo with tarnished judas (not sure if this happens with other characters

**Version information:**
---
 - Installed wave number: Wave 4
 - Version number: 4.6

**Comment by OpenSauce04** [comment]
This issue has been fixed in a future update
