### ISSUE TITLE
Found soul Blighted Dice bug

### ISSUE THREAD

**Issue by tedecti** [OpenSauce04/EpiphanyIssues#27]
**Describe the bug**
---
If character with 2 more items, Blighted Dice and Found Soul try to use blighted dice then the found soul will stop moving, it will open the "inventory" and you can close it only if you throw out the trinket, softlock if you gulp found soul

**Screenshots**
Screenshots attached

**Version information:** 
---
Last steam version, v4.14

**Additional context**
![20221121144348_1](https://user-images.githubusercontent.com/45327704/203005724-2cc82fff-cff5-4622-aaf3-42afe390d271.jpg)
![image](https://user-images.githubusercontent.com/45327704/203005753-e3a84631-c55d-47ce-85b3-635dcb565269.png)
![image](https://user-images.githubusercontent.com/45327704/203005795-455aa919-cfd5-4262-a1cf-29d18fddfbd5.png)
![image](https://user-images.githubusercontent.com/45327704/203005838-ae4d0ab3-ab80-4f57-b6a1-5d4548b7386f.png)

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
