### ISSUE TITLE
Cant select character

### ISSUE THREAD

**Issue by RandomUrpo** [OpenSauce04/EpiphanyIssues#30]
**Describe the bug**
---
when i try to go as tarnished character it just throws me in as ? and doesnt let me choose character

![image](https://user-images.githubusercontent.com/120114588/206476657-36096e0c-d94d-4972-8b3b-861e221d4a8d.png)

![image](https://user-images.githubusercontent.com/120114588/206477588-d81d7994-6a0b-4538-afe3-773055664862.png)

**Comment by Gioshy** [comment]
so I have had this problem is there a way it can be fixed?

**Comment by OpenSauce04** [comment]
Can you please share your mod list? You can provide this by running the EpiphanyDiag.exe program in the mod folder and posting the tar.gz file it provides
