### ISSUE TITLE
Blighted Dice + Schoolbag Duplication

### ISSUE THREAD

**Issue by KaydaCant** [OpenSauce04/EpiphanyIssues#31]
**Describe the bug**
---
With the item schoolbag, and no other active item, using blighted dice or repairing broken dice duplicates itself.

**To Reproduce**
---
Steps to reproduce the behavior: Have schoolbag and only one active item. Repair broken dice or use blighted dice. The dice will duplicate into both schoolbag slots.

**Log**
---
N/A

**Version information:** 
---
 - Installed wave number: Wave 4
 - Version number: v4.15

**Comment by dpower12** [comment]
Fixed internally, expect it soon in the next release, thanks for the report!

**Comment by OpenSauce04** [comment]
Fixed in the v4.21 update
