### ISSUE TITLE
Can not load into game after disabling Epiphany Mod while an Epiphany run was open.

### ISSUE THREAD

**Issue by KattMann00** [OpenSauce04/EpiphanyIssues#32]
**Describe the bug**
I just downloaded the mod for the first time, went to a new run, and selected the door that had appeared in the character selection screen. It brought me to another character select screen, but I had none of the characters. I pressed esc and on the left side of the screen it said i had a run in progress, which confused me because i hadnt selected a character. I then went to the in game mod menu and disabled the mod and closed the game. When i later tried to open the game, the game will open, but when i get to the file select screen and choose my file, the game will crash. I assume this because the mod is disabled while there is a run that needs the mod, but I don't know how to fix this. 
**To Reproduce**
start a new run with epiphany mod, exit the run, disable the mod, close the game, reopen the game.

**Log**
not sure what this is

**Screenshots**
---

**Version information:** 
---
 - Installed wave number: 
 - Version number: 

**Additional context**
i think the problem might be fixed if i could enable the mod from outside the game, but I don't know if there is a way to do this.

**Comment by KaydaCant** [comment]
To enable the mod from outside of the game, go into your mods folder and delete the "disable.it" file in the Epiphany mod folder.

**Comment by OpenSauce04** [comment]
This is a game bug that was fixed in a recent patch. You must be running an outdated or pirated version of the game
Please re-open this issue if this is not the case
