### ISSUE TITLE
tarnished keeper can't pick up fool card

### ISSUE THREAD

**Issue by minebar1** [OpenSauce04/EpiphanyIssues#33]
**Describe the bug**
while playing as tarnished keeper blowing up the marked skull and taking the fool card will just turn it into coins and thus you cannot unlock the door to get to the beast fight

https://user-images.githubusercontent.com/120417808/207148241-211501d4-19d1-4ccd-8add-4fe0b06b14e7.mp4

**Comment by OpenSauce04** [comment]
You get fool cards as TR Keeper from the Depths 2 starting room shop
