### ISSUE TITLE
Tarnished Keeper turning key into coins during Mother's Shadow chase scene

### ISSUE THREAD

**Issue by joshr3** [OpenSauce04/EpiphanyIssues#34]
**Describe the bug**
---
When trying to collect the second knife piece and escape Mother's Shadow, sometimes you are required to collect a key to progress. When collecting this key, it turns into gold, preventing the player from progressing.

**To Reproduce**
---
Steps to reproduce the behavior: Start a game on a seed which you know requires a key to progress in the Mother's Shadow chase scene (my seed in which case is H6ME TVY6). Begin the chase scene by collecting the second knife piece and play as normal until you find the key, which should simply turn to gold upon contact.

**Screenshots**
---
![isaac-ng_1Q6pekWgBD](https://user-images.githubusercontent.com/99200562/207147799-287c82f4-5a74-418e-93e0-b120389ca7d2.png)
You can see in the image that tarnished keeper has 3 coins, no key and a key block blocking its progress.

**Version information:** 
---
 - Installed wave number: Wave 4
 - Version number:  v4.15

**Additional context**
---
Tarnished keeper also does not shoot 5 coin blasts, but rather in a normal Isaac fashion when entering the knife piece 2 subarea. The tears are still coins, though.

**Comment by OpenSauce04** [comment]
Me and another member of the team are unable to replicate this issue

**Comment by CrazyAceking** [comment]
Can confirm this issue, have replicated it. Tarnished Keeper turned the key I needed into coins, softlocked me.
![20230627000627_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/85006082/746819f1-e026-4ba8-8f22-65dae965bd0b)

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
