### ISSUE TITLE
Uhhhh

### ISSUE THREAD

**Issue by IJUSTWANTTOREPORTADAMNBUG** [OpenSauce04/EpiphanyIssues#35]
Even after I've uninstalled and reinstalled the mod, even after the update that fixed it, `corrupted-characters(1)` still shows up on my mod list, but now `epiphany` shows up and that does nothing either. Same problem goes for external descriptions

**To Reproduce**
---
Not sure why it happens for me specifically, but perhaps maybe it's because of one or more mods I have installed

**Log**
---
https://pastebin.com/1nEkdjTz

**Screenshots**
---
https://imgur.com/UQlBQZT

**Version information:** 
---
 - Installed wave number: Wave 4
 - Version number: v4.18

**Additional context**
---
Should I just delete the `corrupted-characters(1)` folder from the tBoI mods folder or is that not safe?

**Comment by OpenSauce04** [comment]
Can you please share your mod list? You can provide this by running the EpiphanyDiag.exe program in the mod folder and posting the tar.gz file it provides
