### ISSUE TITLE
Question mark character

### ISSUE THREAD

**Issue by Dejnov-123** [OpenSauce04/EpiphanyIssues#36]
**Describe the bug**
---
Whenever I go into the tarnished character door it changes me into a black character with question mark on it. I cant move or access the menu and I had to use Ctrl alt delete to exit.

**To Reproduce**
---
Steps to reproduce the behavior: It happened when I downloaded the mod then turned on the game and went into the Tarnished door.

**Log**
---

**Screenshots** 
---

![image](https://user-images.githubusercontent.com/79438795/207181051-3e2abc8b-f1c6-4ef9-a24b-4a1215771658.png)

**Version information:** 
---
 - Installed wave number: 
 - Version number: Repentance 1.7.9b

**Additional context**
---

**Comment by OpenSauce04** [comment]
Can you please share your mod list? You can provide this by running the EpiphanyDiag.exe program in the mod folder and posting the tar.gz file it provides
