### ISSUE TITLE
Tarnished Isaac doesn't get Guppy transformation

### ISSUE THREAD

**Issue by Notorial** [OpenSauce04/EpiphanyIssues#44]
**Describe the bug**
---
Guppy's Tail, Guppy's Eye, and Guppy's Collar do not give the Guppy transformation when all are in the inventory.
Even if they are put back down and picked back up.
I believe I touched Guppy's Paw earlier in the run, but I could be confusing runs lol.

**To Reproduce**
---
Get Guppy's Collar
Get Guppy's Tail
Get Guppy's Eye
Get all three items in inventory with no particular order
???
Profin't
---

**Screenshots**
---
![Screenshot (745)](https://user-images.githubusercontent.com/102758057/216736360-f282fe8e-1b21-4a5b-b970-313b289f18cd.png)

**Version information:** 
---
 - Installed wave number: 
 - Version number: 

**Additional context**
---

**Comment by OpenSauce04** [comment]
This appears to be some strange quirk of the base game, as following the same steps with vanilla Isaac also leads to no transformation.
