### ISSUE TITLE
Epiphany always freezes my game

### ISSUE THREAD

**Issue by GhostDuck0** [OpenSauce04/EpiphanyIssues#46]
**Describe the bug**
---
Whenever I load the game with epiphany it freezes upon loading or starting a run

**To Reproduce**
---
Load or start any type of run with epiphany installed

 

**Screenshots**
---
N/A

**Version information:** 
Cant get to the console without loading a run
 - Installed wave number: 
 - Wave 4
 - Version number: 
 - Cant find out

**Additional context**
I deleted every mod except epiphany and It still didn't work, unistalled and reinstalled the game and verified the game files but nothing has worked.
---

**Comment by OpenSauce04** [comment]
Can you please attach your EpiphanyDiag file às the issue template stated?

**Comment by GhostDuck0** [comment]
Sorry, here it is
[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/10610866/EpiphanyDiagnostics.tar.gz)

**Comment by ArekusuP** [comment]
I have the same problem

**Comment by OpenSauce04** [comment]
@GhostDuck0 Your final log seems to show that you closed Isaac completely on your own?
Can you verify that this bug is still happening?
If you do not respond, I will close this issue in 5 days

**Comment by GhostDuck0** [comment]
The game freezes and then stops responding so I have to close it, and yes, the bug is still happening.

**Comment by OpenSauce04** [comment]
Upon closer inspection, I have found the issue. I will investigate

**Comment by OpenSauce04** [comment]
This issue has been fixed in 4.26
