### ISSUE TITLE
Tarnished Isaac Active Buggy

### ISSUE THREAD

**Issue by LenoPlanet** [OpenSauce04/EpiphanyIssues#47]
**Describe the bug**
---
Whenever I use my Blighted Dice the Item activates but it does nothing. 

**To Reproduce**
---
1. Pick Tarnished Isaac
2. Pick up a Item
3. Try to use the Dice

**EpiphanyDiag info**
---

**Screenshots**
---

**Version information:** 
---
 - Installed wave number: 
 - Version number: 

**Additional context**
---

**Comment by OpenSauce04** [comment]
Please fill out the `EpiphanyDiag info` section of the template or we can't help you
