### ISSUE TITLE
Green Gold Items

### ISSUE THREAD

**Issue by Dredgen-Xul** [OpenSauce04/EpiphanyIssues#48]
After unlocking golden items they appear as a green color instead of gold. I’ve gone through and uninstalled every mod and even tried reinstalling both epiphany and TBOI. Nothing has fixed it so far. The screenshot was taken with a mod to spawn items in the starting room  but happens regardless of that mod. I’m also on a steam deck if that matters. Everything is updated as current as possible.

![image](https://user-images.githubusercontent.com/125776949/219907941-b2b3a63b-fe93-4802-a3eb-20014732ce33.jpg)

**Comment by OpenSauce04** [comment]
This is a known issue with Proton, we sadly cannot fix it, as it is an issue with the game itself
