### ISSUE TITLE
Turnover just refuses to work sometimes.

### ISSUE THREAD

**Issue by Meatsofa** [OpenSauce04/EpiphanyIssues#49]
(DISCLAIMER)
I have a lot of mods installed, so this may or may not be a conflict of some kind.
---------------------------------

After the recent update i have found that i am randomly unable to use turnover in curse rooms.
the room appears as cleared and there are no enemies but the turnover is still just a ?.

this happened twice in one run, if it means anything both times there was a devil statue in the curse room.
going to the flipside of a curse room with a statue in it worked fine for some reason.

another curse room that had no statue also worked.
(this was all in one run)

also, turnover does nothing if there is a quality 4 item on the ground but i have not seen this documented anywhere.
as in, i went to the wiki and nowhere does it state that quality 4 items should stop you from turning them over.

**Comment by OpenSauce04** [comment]
Please attach your diagnostic info, the template says how to do so for a reason

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
