### ISSUE TITLE
epiphany don't working

### ISSUE THREAD

**Issue by audigy1305** [OpenSauce04/EpiphanyIssues#51]
i tried to download epiphany from different sources, but it doesn't seems to work. When i'm trying to unlock any tarnished character or use any epiphany item, nothing happens
![image](https://user-images.githubusercontent.com/77286539/227487171-760e8c2a-118f-4835-806c-cb8a265f407f.png)

**Comment by OpenSauce04** [comment]
Please follow the issue template
