### ISSUE TITLE
Turnover breaks  if "No Pickup Cap" is also running

### ISSUE THREAD

**Issue by SnoillerFitzroy** [OpenSauce04/EpiphanyIssues#52]
If the mod "No Pickup Cap" is installed and running alongside Epiphany, Tarnished Keeper's Turnover doesn't work while holding more than 9 coins

* Have "No Pickup Cap" installed (https://steamcommunity.com/sharedfiles/filedetails/?id=1309404579)
* Pick up a total of at least 10 coins as Tarnished Keeper
* In a normal room, Turnover will say it needs 6 coins to activate, but won't trigger even though you have more than 6 coins

**EpiphanyDiag info**
I can't get the diagnostic executable to run. Trying to open the zip gives an error saying it's an unknown type or corrupted. (renamingto remove ".zip" gives "this can't run on your PC" error)

**Version information:** 
 - Installed wave number: Wave 4
 - Version number: 4.26

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
