### ISSUE TITLE
Animation Break For Tarnished Keeper

### ISSUE THREAD

**Issue by Sweg1b01** [OpenSauce04/EpiphanyIssues#54]
**Describe the bug**
---
This Bug is the result of having the epiphany mod, pog for good items mod and specialist dance for good items mod which breaks tarnished keeper's animations and gets it stuck on the specalist dance animation

**To Reproduce**
---
all you need to do is find a q4 item and it will lock tarnished keeper into the specalist dance animation, if you find a q3 item after finding a q4 item it will play the animation normally but delete the body of tarnished keeper

**EpiphanyDiag info**
---
i cant extract the diag bc of a zip error

**Screenshots**
---

https://user-images.githubusercontent.com/81667660/229684425-2de2e467-7c00-4c1c-af6f-799be23b30c8.mp4

**Version information:** 
---
 - Installed wave number: Wave 4
 - Version number:  v4.26

**Additional context**
---
the animation files of all 3 mods has something to do with this bug if the glitch evidence doesnt show up i can send via discord/email if needed this is really the only consistant glitch ive had and i hate it

**Comment by Sweg1b01** [comment]
ive also set in the mod settings of specialist dance to only activate for q4 items

**Comment by An-Annoying-Cat** [comment]
im pretty sure this is just a general issue that occasionally occurs with the specialist dance mod

**Comment by Sweg1b01** [comment]
it doesnt break this hard though and do you know any mod that does this kind of animation break?

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
