### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by MichaelAfton51** [OpenSauce04/EpiphanyIssues#56]
ever since i unlocked tarnished keeper the game would crash when i try to click on the door in the character select screen

**Comment by MichaelAfton51** [comment]
i just tested it on other files and it doesn't crash even with all my mods but on my main file it just doesn't work

**Comment by MichaelAfton51** [comment]
i kinda fixed it but it takes like 5 minutes to load if i don't click anything idk if there is a way around that but it would be nice if there was

**Comment by OpenSauce04** [comment]
Follow the template
