### ISSUE TITLE
So many bugs

### ISSUE THREAD

**Issue by MooMcMooman** [OpenSauce04/EpiphanyIssues#57]
**Describe the bug**
---
All of the menus don't show up

**To Reproduce**
---
Use anything menu related

**EpiphanyDiag info**
---
This can't extract (might be another bug)

**Screenshots**
---

![20230421210608_1](https://user-images.githubusercontent.com/131305003/233753881-284bf7bc-a5ef-4f4f-8f6c-5faba71a3626.jpg)
![20230421211235_1](https://user-images.githubusercontent.com/131305003/233754039-e80ea661-c1b4-4ecc-850e-932bd6dfcc88.jpg)
**Version information:** 
---
 - Installed wave number: 4
 - Version number: Won't show up (yet another bug)

**Additional context**
---

**Comment by OpenSauce04** [comment]
This issue is too vague for me to solve, although from the sounds of it I can assume that you might be using a pirated version of the game

Open another issue if you can produce something we can work with outside of "there are bugs"
