### ISSUE TITLE
Tr Characters portraits not appearing w/ modded bosses

### ISSUE THREAD

**Issue by NotSpooky54** [OpenSauce04/EpiphanyIssues#6]
**The bug**
Literally the title says, what else i can put here
Dunno
Ya mama

**To Reproduce**
Enter a boss room with a modded boss inside while playing a Tarnished Character
Ive seen this only as Tarnished Keeper and Fiend Folio bosses

-- Be Tarnished Character
-- Enter boss room with modded boss
-- ???
-- bug achieved

**Log**
I have no clue why but my log dosent exist
And also this is a graphical bug so i think the log is fine lol

**Screenshots**
![unknown-10](https://user-images.githubusercontent.com/107282165/196004969-e8ec35af-afa7-432f-bd15-04fb11fe7abf.png)

**Version information:**
Second patch of wave 4

**Additional context**
Blame stage api

**Comment by OpenSauce04** [comment]
I have no idea how to fix this, StageAPI has no documentation on stage transition sprites or anything of the like

**Comment by OpenSauce04** [comment]
This issue will be fixed in the v4.11 update
