### ISSUE TITLE
K.A.E.K (aka Stanley) is ripping me off

### ISSUE THREAD

**Issue by Enzo2721** [OpenSauce04/EpiphanyIssues#60]
Describe the bug 
K.A.E.K is expiring even after renewal
To Reproduce
Start Greedier with Tainted Keeper,get the K.A.E.K, renew it,go to next floor.
EpiphanyDiag info
Epiphany Diagnostics Tool 2.0 | Written by OpenSauce
Source available at: https://github.com/OpenSauce04/EpiphanyDiag
ERROR 2: This program is being run outside of the Epiphany folder.
Press any key to exit.
Looks like this
Screenshots
Before:
![20230506204142_1](https://user-images.githubusercontent.com/132752364/236622274-e32c999f-c630-4f57-9ebd-176b970767dc.jpg)
After:
![20230506204153_1](https://user-images.githubusercontent.com/132752364/236622283-fde4d74a-51d2-46a8-8418-53606d7fe225.jpg)

Version information:
Installed wave number: Wave 4
Version number: v4.26.1

**Comment by Enzo2721** [comment]
Guess what?
Apparently, this is a mod compatility problem...
With Greed mode Alt Path mod.
Sorry for disturbing you.

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
