### ISSUE TITLE
Isaac crashes with black screen

### ISSUE THREAD

**Issue by YaPredalHrista** [OpenSauce04/EpiphanyIssues#61]
Isaac crashes when trying to start the game
---
When i open isaac is sits at back screen at about 3~4 seconds and crashes

**To Reproduce**
---

I started a run with tainted lilith (for the first time) and it crashed? i couldnt play the game with epiphany ever cince

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/11412439/EpiphanyDiagnostics.tar.gz)

**EpiphanyDiag info**
---

**Screenshots**
---

**Version information:** 
---
 - Installed wave number: 
 - Version number: 

**Additional context**
---

**Comment by OpenSauce04** [comment]
Please use the official mirror from the link on the Steam Workshop, 3rd party versions of the mod often break
