### ISSUE TITLE
the whole mod just doesn't work

### ISSUE THREAD

**Issue by talos222** [OpenSauce04/EpiphanyIssues#64]
The whole mod just doesn't work. The characters don't seem to exist and the items have blank textures and don't do anything. There is a blank character that appears when the mod is enabled that doesn't spawn with any items or anything not even a texture.

Im not sure how to reproduce the bug

**Comment by mohsin4547** [comment]
try to put --luaheapsize 0 in the game's launch commands

**Comment by OpenSauce04** [comment]
There is not enough information to help you; If you are still having this problem, please re-submit an issue with diagnostic information attached as per the issue template
