### ISSUE TITLE
Descent and other items don't work.

### ISSUE THREAD

**Issue by ZeraExists** [OpenSauce04/EpiphanyIssues#65]
It's mainly just descent but that and some other items just don't seem to work for me. It's not just with this mod but I just figured yall would maybe have some fix. So whenever I use it the shadows and tarnished judas still blink like it would work, but the attack does not come out nor do I teleport when using it. Just wanted to know if you have an idea on how to fix it, my main theory is that I have a TON of mods on and that's probably what's causing it.

**Comment by ZeraExists** [comment]
The same thing happens with spindown/spinup die if that matters at all

**Comment by OpenSauce04** [comment]
I can't help you unless you post the diagnostic data as per the issue template
