### ISSUE TITLE
Getting the wrong unlocks as Tarnished Isaac?

### ISSUE THREAD

**Issue by xander3000** [OpenSauce04/EpiphanyIssues#67]
### Preamble

- [X] I am either using the Steam Workshop version of the mod, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

According to the Epiphany Wiki, I'm supposed to Unlock Dad's Wallet after beating Isaac, ????, Satan and Lamb, but I got Mother's Shadow instead and I haven't even beaten Mother with him yet. Unsure if that's a game problem or the Wiki is wrong.
https://tboi-epiphany.fandom.com/wiki/Tarnished_Isaac#Unlocks

### Screenshots

![20230529203309_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/14163461/e3a58229-20f2-4170-8de6-c00ae313a851)
![20230529203342_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/14163461/015f4f66-dc28-4c8a-9aa5-999276aa37c4)
![20230529203347_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/14163461/46c49cfb-9e8c-4b0f-8634-cf553a8d7d03)

### Steps to Reproduce the Issue

Beating Isaac, ????, Satan and Lamb for the first time as Tarnished Isaac without beaten Mother before.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/11594710/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
One look at the wiki will tell you there is nothing wrong here
