### ISSUE TITLE
Tainted Cain Co-op Crash

### ISSUE THREAD

**Issue by Magebones** [OpenSauce04/EpiphanyIssues#69]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

While playing Co-op with Tainted Cain as a character, if T. Cain dies, the game crashes.

### Steps to Reproduce the Issue

Go into Greed Mode, have one character be Tainted Cain, and any other character joins.
Then have Tainted Cain stand in the Curse Room doorway until he dies.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/11659687/EpiphanyDiagnostics.tar.gz)

### Additional Context

I have some other mods installed, but they don't seem to be the conflict that's causing this issue.
I thought it was something to do with Co-op ghost costumes, but that's not it.
This issue only appears when Epiphany's installed.

**Comment by OpenSauce04** [comment]
Closing this due to Wave 5's release; The codebase of Wave 4 is so different to Wave 5 that we can't be sure that any of these bugs still exist. If you encounter the bug again, please post a new report.
