### ISSUE TITLE
TR Keeper Breaks Down Fiend Folio's Stud Pickups Into Coins

### ISSUE THREAD

**Issue by emihead** [OpenSauce04/EpiphanyIssues#70]
### Preamble

- [x] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

Title is self-explanatory. This makes the Brick Figure item from FF a one-item break for TR Keeper, as its effect of replacing coins with studs can give you infinite coins extremely easily. I brought it up in the FF server and a dev said it was something Epiphany would have to fix. 

### Steps to Reproduce the Issue

1. Install both Epiphany and Fiend Folio
2. Play as Tarnished Keeper
3. Get the Brick Figure item from a shop
4. Try picking up a stud

### Diagnostics Information

https://drive.google.com/file/d/1CGqXfK8b2LR_2O0KtevQrem0WMwyxUoy/view?usp=sharing

**Comment by OpenSauce04** [comment]
This issue has been fixed in a future update
