### ISSUE TITLE
Tarnished characters get stuck dancing with specialist

### ISSUE THREAD

**Issue by TeamSkullEliteCross** [OpenSauce04/EpiphanyIssues#72]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

any time Specialist dance triggers. the tarnished characters get stuck after the item they are dancing for disappears. can someone please look into this?

### Screenshots

![image](https://github.com/OpenSauce04/EpiphanyIssues/assets/141066629/3b02dcff-70a5-4033-934d-531686384a20)

### Steps to Reproduce the Issue

simply finding an item that causes your tarnished character to dance causes this.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12218107/EpiphanyDiagnostics.tar.gz)

**Comment by SiwwiSiwwi** [comment]
I remember this happening to me one time

**Comment by OpenSauce04** [comment]
This is an issue with the Specialist mod, and isn't related to us.
