### ISSUE TITLE
K.A.E.K Mod Incompatibility

### ISSUE THREAD

**Issue by Enzo2721** [OpenSauce04/EpiphanyIssues#73]
Preamble

I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
Yes
I am playing on v1.7.9b of The Binding of Isaac: Repentance
Yes
I have tried installing the Mod Error Container mod before filing this issue
Yes

What Happened?

After paying Stanley to not expire the K.A.E.K, it expires. I suspect it's the same mod incompatibilty with Alt Path Greed Mode.
Also the sign is spazing out, I don't know why but it was funny.

Screenshots
![20230801233812_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/132752364/a15535f0-cafd-445b-a031-3afdd893e08d)
![20230801233837_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/132752364/e59f76ae-0c93-4188-91a4-663ba1b924d9)

Steps to Reproduce the Issue
Open a Greedier game with the mod stated above (Alt Path Greed Mode)
Go to the secret room, get the K.A.E.K
Complete the floor as normal
Pay Stanley His 15 coins.
Go to next floor.

Diagnostics Information
Epiphany Diagnostics Tool 2.1.1 | Written by OpenSauce
Source available at: https://github.com/OpenSauce04/EpiphanyDiag
ERROR 2: This program is being run outside of the Epiphany folder.

Additional Context
I'm very sorry it's the same problem. I know you're very busy and the fact I can just disable the mod.
I still don't know how to open the Diag Info file.

**Comment by OpenSauce04** [comment]
Due to the lack of a diagnostic file, this cannot be properly investigated, however I'll attempt to recreate the issue with Alt Path Greed Mode installed, and if the issue occurs, I will add it to our diagnostic blacklist. Thanks for the report.
