### ISSUE TITLE
Dice Machines do not work while achievement bypass is active

### ISSUE THREAD

**Issue by PennyCLMU** [OpenSauce04/EpiphanyIssues#74]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

Dice Machines spawn nothing upon being given five cents, unless they explode and give the Portable Dice Machine, which also does not work. The pocket dice items still exist and function as expected, but they are effectively unobtainable due to the machines not working. All of these only apply while achievement bypass is active and that is all.

### Steps to Reproduce the Issue

. Spawn a dice machine and play it while achievement bypass is active
. Spawn a dice machine and play it while achievement bypass is inactive

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12254572/EpiphanyDiagnostics.tar.gz)

### Additional Context

is there another thing I can do to mess around with unlocked stuff that doesn't cause features to break?

**Comment by PennyCLMU** [comment]
Update: Dice Machines have suddenly stopped working again, with and without achievement bypass

**Comment by OpenSauce04** [comment]
I can't replicate this issue in the latest release, so I'm going to assume it was fixed some time between the report and now. Thanks for the report.
