### ISSUE TITLE
Tr-Judas pays devil deals with heart containers

### ISSUE THREAD

**Issue by MigoNorrea** [OpenSauce04/EpiphanyIssues#76]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

I entered a devil room with Tarnished Judas, and based on the info on https://tboiepiphany.wiki.gg/wiki/Tarnished_Judas , I was expecting to pay with broken hearts. I took a deal thinking it could be a visual bug, but it killed me due to my low health.

### Screenshots

![Binding of Isaac_ Repentance 05_08_2023 20_14_49](https://github.com/OpenSauce04/EpiphanyIssues/assets/141518179/675c378a-d5d0-41b2-a8ec-f060aefb168d)

### Steps to Reproduce the Issue

Just going into a devil room, I didn't have any unusual items

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12267877/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
Please try installing the "Mod Error Container" mod, and share whether or not his issue still happens

**Comment by OpenSauce04** [comment]
This issue was fixed in a previous update. Thanks for your report
