### ISSUE TITLE
Character-Choosing Menu Skipped When Quick Restart

### ISSUE THREAD

**Issue by ZeanKey** [OpenSauce04/EpiphanyIssues#78]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

When pressing Tab + R in the mod's characters menu, the game will wrongly started.
Also, while playing the T.R. characters, pressing Tab + R in a rapid speed will make the game jump back to the T.R. characters' menu.

### Screenshots

https://github.com/OpenSauce04/EpiphanyIssues/assets/65109006/c72e35a4-9cce-428d-bdd4-8a8993ea70f6

### Steps to Reproduce the Issue

Enter the T.R. characters' menu. Press Tab + R to trigger quick restart (this can also be triggered by press R when holding Tab). And the game will start with an error character.

When playing a T.R. character, trigger quick restart rapidly will cause the game return to the character choosing menu.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12388284/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
Tab + R? Is this a vanilla thing? I've never heard of it before

**Comment by ZeanKey** [comment]
I'm sorry for this mistaken report, this bug is actually caused by another mod called Good Trip, which provide the function of quick restart. It's my fault.
