### ISSUE TITLE
Reverse Emperor gives checkmark/essence achievement on Hush floor

### ISSUE THREAD

**Issue by DasWeedAndru** [OpenSauce04/EpiphanyIssues#79]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

So i was playing Tr Cain for unlocks and in a run i had a reverse emperor card on me. I made my way to bossrush and then to hush to complete both in the same run. When i entered i thought to use my reverse emperor to grab another item to craft another bag. After beating the womb boss i got the essence achievement but i didn't fought the hush and the checkmark was there. Then, after finishing my run i move to my third file to test and it happened again. This test i had only the epiphany and mod error active to check. Then i thought to see if in vanilla and after removing my third dead god file and with a fresh safe file it didn't show the checkmark.

### Screenshots

https://github.com/OpenSauce04/EpiphanyIssues/assets/134204086/f1726da6-e5a1-4933-be6c-5c8fe2544a40

### Steps to Reproduce the Issue

Start as you normaly do and go for a hush fight. Find a reverse emperor card and use before the fight. Fight that boss and if you had the bossrush check you would unlock the essence achievement otherwise the fight will count for the husk check

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12464163/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
A fix has been developed, and will release in a future update. Thanks for the report

**Comment by OpenSauce04** [comment]
The fix has been released in 5.3.4
