### ISSUE TITLE
Hush door despawned when it shouldn't have as TR. Keeper

### ISSUE THREAD

**Issue by IJUSTWANTTOREPORTADAMNBUG** [OpenSauce04/EpiphanyIssues#8]
The Door to Hush despawned when I left the boss room as TR. Keeper, as the name would imply

Repor
---
Step 1: Select TR. Keeper
Step 2: Reach Mom's Heart/It Lives and beat it within 30 minutes
Step 3: Use Turnover
Step 4: Leave Boss Room and Re-enter (still before 30 minutes)
And presto, you've just screwed yourself out of getting the Hush Mark!

---

Screenshot:

![20221016024740_1](https://user-images.githubusercontent.com/115917204/196023041-4b699468-d722-4e45-b719-984ee0a91419.jpg)

---
 - Installed wave number: Wave 4
 - Version number: V 4.2

---

Unrelated note: I absolutely hated having to make a github account just to post my issue here. Not your fault, don't worry.

**Comment by OpenSauce04** [comment]
If this issue is still occurring, please post a new issue report with updated info and logs
