### ISSUE TITLE
TR Keeper gets only punished when taking Soy Milk, losing tears and damage.

### ISSUE THREAD

**Issue by TheObserver-sys** [OpenSauce04/EpiphanyIssues#80]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

While generating items to purchase, came across Eden's Blessing and Soy Milk. Took Blessing first, then Soy Milk, expecting even higher tears than before. Instead, I received the damage down of soymilk, and severe tears down.

Near the start of the run, admittedly, I did use the D100 to try and roll myself a better item -- which gave me a drastic tears up, but it shouldn't have triggered roll around  even with the mult boost.

### Screenshots

![image](https://github.com/OpenSauce04/EpiphanyIssues/assets/58029438/ab8a0ab7-e3da-4114-98c6-0cefff748e7c)
![image](https://github.com/OpenSauce04/EpiphanyIssues/assets/58029438/b0edd875-65e5-49d8-97c6-8c0bc555cf85)

### Steps to Reproduce the Issue

Assuming it isn't a rollover bug, which I don't **think** it is:

- Roll a tears mult up with D100 or D8
- Get/Spawn in Soy Milk
- Marvel at the lack of fire rate given.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12615910/EpiphanyDiagnostics.tar.gz)

### Additional Context

It might also have something to do with collecting purity and then soy milk at the same time, so in the event it is, try that too, I suppose.

**Comment by OpenSauce04** [comment]
We're aware of the issues with Tarnished Keeper's tears formula, and are working to address it for the Wave 6 update. Thanks for the report

**Comment by OpenSauce04** [comment]
This issue has been fixed internally, and will be addressed in the Wave 6 update. Thanks for your report
