### ISSUE TITLE
K.A.E.K Tainted cain bug

### ISSUE THREAD

**Issue by OvalCakeBoy1** [OpenSauce04/EpiphanyIssues#81]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

So when I went to greed mode with tainted cain the weird looking rock was there and I broke it, I didnt pick it up mind you, I then went in to the shop and came out of it seeing a K.A.E.K card

### Screenshots

![what](https://github.com/OpenSauce04/EpiphanyIssues/assets/145724886/5b47cd8f-536e-400c-a070-c843e43a517e)

![what the hell is this doing here](https://github.com/OpenSauce04/EpiphanyIssues/assets/145724886/280bef80-da96-4da3-93a8-09de5483b233)

![loal](https://github.com/OpenSauce04/EpiphanyIssues/assets/145724886/603c0b8a-92f2-46e5-b891-ee0506900924)

### Steps to Reproduce the Issue

 1. Go in to greed as tainted cain
 2. find weird looking rock
 3. bomb it
 4. get shiny rock
 5. leave the room then re enter
 6. its now a K.A.E.K card
 7. pick it up, its now in my inventory
 8. it must have been stacked on shiny rock because here it is again
 9. pick up shiny rock to get the bag thing

### Diagnostics Information

 [EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12615910/EpiphanyDiagnostics.tar.gz)

(Im not sure if this is it im new here)

### Additional Context

I really REALLY want to know if I get all the hay and then enter a sacrfice room (I have a mod that makes it so I get different rooms in greed)

**Comment by OpenSauce04** [comment]
This bug was fixed in a prior update. Thanks for the report
