### ISSUE TITLE
Eden mission doesn't show how many debugged items we had

### ISSUE THREAD

**Issue by MrMatzn** [OpenSauce04/EpiphanyIssues#82]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

I was attempting to unlocking that achievement, but i dont don't know how many items i had have debugged

### Screenshots

![20231004225755_1](https://github.com/OpenSauce04/EpiphanyIssues/assets/147022360/fe86761a-b112-42c1-8e8e-08ee25ee6d1b)

### Steps to Reproduce the Issue

Spawn a Passive Item, Debug that item, Press C to check the menu and go to: UNLOCKS/ACHIEVEMENTS/MISCELLANEOUS/EDEN HOLDS AN EXTRA ITEM

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12812476/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
This issue has been fixed in a previous update. Thanks for your report
