### ISSUE TITLE
Pocket items dont work.

### ISSUE THREAD

**Issue by Richter4444** [OpenSauce04/EpiphanyIssues#83]
i tried using the pocket items, it only seems to affect Tarnished characters.

i tried disabling most mods i have, but i cant pinpoint the one thats keeping the pocket items from working,

for example.
TR keepers turnover does NOTHING.

TR Isaacs blighted dice consumes charges, but doesnt reroll or dissapear items on activation.
but it WILL consume items if its uncharged.

**Comment by OpenSauce04** [comment]
Please repost the report, this time following the issue template
