### ISSUE TITLE
TR magdaline problem

### ISSUE THREAD

**Issue by gani132** [OpenSauce04/EpiphanyIssues#84]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

every time i i get bleeding heart, the non-achievment item shows up, with a simbol of epiphany on the side, this make impossible to me to get tr magdaline 

### Steps to Reproduce the Issue

i get the bleeding heart, even with the debug mode 

### Diagnostics Information

[README_PROD.txt](https://github.com/OpenSauce04/EpiphanyIssues/files/13480291/README_PROD.txt)

**Comment by OpenSauce04** [comment]
You attached the readme file of the diagnostic program rather than the file it generated. Please resubmit the issue with the correct file
