### ISSUE TITLE
EID compatibility script causes errors in the console

### ISSUE THREAD

**Issue by goob8079** [OpenSauce04/EpiphanyIssues#86]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

Every time I try to play, an error message keeps popping up.  However, I don't think it affects gameplay, not that I have noticed anything unusual.

Here is what the error says:

"MC_POST_RENDER" from "Epiphany" failed: .../mods/epiphany_3012430463/scripts/helpers/hud_helper.lua:124: bad argument #1 to 'add' (Vector expected, got nil)
Stack Traceback:
  in method add
  .../mods/epiphany_3012430463/scripts/helpers/hud_helper.lua:124: in function 'GetCustomHUDOffset'
  ...430463/scripts/compatibility/patches/eid/eid_support.lua:67: in function at line 65

### Steps to Reproduce the Issue

- Start a game with any character and the error message pops up

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/13986460/EpiphanyDiagnostics.tar.gz)

**Comment by swenderman** [comment]
"MC_POST_RENDER" from "Epiphany" failed: .../mods/epiphany_3012430463/scripts/helpers/hud_helper.lua:124: bad argument #1 to 'add' (Vector expected, got nil)
Stack Traceback:
  in method add
  .../mods/epiphany_3012430463/scripts/helpers/hud_helper.lua:124: in function 'GetCustomHUDOffset'
  ...430463/scripts/compatibility/patches/eid/eid_support.lua:67: in function at line 65

same here

**Comment by OpenSauce04** [comment]
We're aware of this issue, and are working to fix it. Thanks for the report

**Comment by OpenSauce04** [comment]
This issue has been addressed internally and the fix will be released in a future release. This will likely be the Wave 6 update

**Comment by OpenSauce04** [comment]
The fix has been released in 5.3.4
