### ISSUE TITLE
Debug item, bugged

### ISSUE THREAD

**Issue by ArcadeRice** [OpenSauce04/EpiphanyIssues#89]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

Whenever I use the Debug item, it makes my character stuck, ending my run. What it should do is to let me pick an item from 3 options, but instead, I'm unable to move, can't click away, close/re-open the game doesn't work, and can't kill myself to fix it. 

### Screenshots

![Screenshot (531)](https://github.com/OpenSauce04/EpiphanyIssues/assets/158355436/87398557-ad3d-43f8-8064-712d6f9589ec)

### Steps to Reproduce the Issue

* Activate Debug item
* Bug happens

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/14117376/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
The diagnostic file produced the following warnings:
```
!!Mod Config Menu - Continued: High Severity
The Specialist for Good Items: Medium Severity
Stats+: Low Severity

Mod Error Container is missing.
```
Try addressing these issues, then see if the issue still happens

**Comment by OpenSauce04** [comment]
Due to the lack of response, I am going to have to assume that the issue is caused by the previously flagged mods. If you experience this issue again after taking the above measures, please open a new issue
