### ISSUE TITLE
Bug with repentogon

### ISSUE THREAD

**Issue by pokiakjsf** [OpenSauce04/EpiphanyIssues#90]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

When playing with repentogon, every time i play, my character leaves a trail of isaac sprites, making gameplay annoying, and it makes every character do contact damage, and when i touch a wall or obstacle(rocks, etc) i bounce off it

### Steps to Reproduce the Issue

Play epiphany with repentogon installed

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/14251876/EpiphanyDiagnostics.tar.gz)

### Additional Context

It doesnt give an error in the diagnostic so i dont know what it could be

**Comment by Jujulues** [comment]
Can you try disabling Furtherance for me? That mod spat out quite a few errors in your most recent log
![image](https://github.com/OpenSauce04/EpiphanyIssues/assets/154038336/262f9b3d-d733-41e5-88eb-f88406c5cb13)
There was another concerning thing but I want to see if there was a conflict between Epiphany and Furtherance that caused this. Let me know if the issue persists after you disable it.

**Comment by pokiakjsf** [comment]
Its not furtherance, i always get those errors with or without epiphany

**Comment by OpenSauce04** [comment]
This definitely seems like some kind of malfunction in another mod or an incompatibility, as none of the behaviour described is implemented in Epiphany

Have you tested to make sure that these issues only happen if Epiphany is enabled?

**Comment by pokiakjsf** [comment]
Yes, ive turned off mods one by one until i reached epiphany and it got fixed

**Comment by OpenSauce04** [comment]
I just noticed, your Epiphany version is horribly outdated. You're running Epiphany 5.0.4, a version released in August of last year. This is likely contributing to or entirely causing the issue

I see you're not running Isaac through Steam, so please download an updated copy of the mod from here:https://gamebanana.com/mods/381475

**Comment by pokiakjsf** [comment]
Thanks, i didnt know, i will update it and tell yiu if it works

**Comment by pokiakjsf** [comment]
It was that, i didnt know it was outdated, it works fine now
