### ISSUE TITLE
Tarnished Characters not unlockable bug

### ISSUE THREAD

**Issue by ErikolGamer14** [OpenSauce04/EpiphanyIssues#93]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I have checked that I am running the latest version of Epiphany
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing either the 'Mod Error Container' mod or Repentogon before filing this issue

### What Happened?

I'm trying to run the mod (with other mods installed) and I'm able to do the things needed for unlocking characters. such as playing as tainted cain and get the wheat to fight and unlock the characted, do a devil and angel pact on same run as tainted judas, etc. but not of this when going to the tarnished characters screen gets any character to be playable.

Additionally, I've been trying to play with "Mod error container mod" and then I've tried with Repentogon but it's the same

### Screenshots

(I can provide screenshots but what I explained at the top I think is self explainatory)

### Steps to Reproduce the Issue

- (Mod list: https://steamcommunity.com/sharedfiles/filedetails?id=3172687710)
- Play to unlock character.
- Go to tarnished character selection screen.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/14474806/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment]
Could you try removing the Specialist mod and seeing if that fixes the issue?

Feel free to use debug commands to help speed up the process of going through the unlock method to check

**Comment by OpenSauce04** [comment]
Due to lack of response, I am going to make the assumption that Specialist was the cause of the issue, and close the issue

If the issue still occurs after removing that mod, please open a new issue
