### ISSUE TITLE
Tarnished Samson Coop Crashes the game

### ISSUE THREAD

**Issue by Maxi90909** [OpenSauce04/EpiphanyIssues#94]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I have checked that I am running the latest version of Epiphany
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing either the 'Mod Error Container' mod or Repentogon before filing this issue

### What Happened?

When I play alone as tarnished samson the game works fine. But when I play with a friend and tarnished samson is one of the characters, the game crashes shortly after tarnished samson smashes the floor, rocks drop and the other player picks up the rocks and trows them. The rocks then travel through the wall without scaddering into rocks and if I then use any console command the game instantly crashes.

### Steps to Reproduce the Issue

1.Play as t. Samson (start the game with him or add him with coop)
2. Play a bit (Usually until the first boss) 
3. After clearing the boss smash the floor and the other player (not t. samson) has to pick up the rocks and trow them.
4. The rocks go through the wall, then open the console and type any command like spawn a dime. 
5. Instant crash.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/14575571/EpiphanyDiagnostics.tar.gz)

I hope I did this correctly

### Additional Context

I have a lot of mods. I am going to remove 2 of the 3 mods the programm mentioned

**Comment by OpenSauce04** [comment]
Please test after removing the following mods:
- Heart tokens for the Lost
- Fancy Costumes
- The Philosopher's Stone

If the issue still occurs, please open a new issue
