### ISSUE TITLE
Epiphany active items don't trigger effects on use

### ISSUE THREAD

**Issue by TarnishedCain** [OpenSauce04/EpiphanyIssues#95]
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I have checked that I am running the latest version of Epiphany
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing either the 'Mod Error Container' mod or Repentogon before filing this issue

### What Happened?

Use any active item, nothing happens. Pretty sure this isnt meant to happen?

### Screenshots
[Mod list screenshot spam removed]

### Steps to Reproduce the Issue

Unsure. All I know is that active items don't work. I'll  attach screenshots of my mods in case there are conflicts you may be able to find.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/14575750/EpiphanyDiagnostics.tar.gz)

**Comment by TarnishedCain** [comment]
Yes, i removed the mods it told me to after running EpiphanyDiag. It did not help, though.

**Comment by OpenSauce04** [comment]
It's important to note that after removing problematic mods, the game must be restarted. If the game is not restarted, issues caused by other mods may still persist until the game is closed and reopened.

Just to be sure that they aren't the issue, try to replicate the issue again now that the game has been closed and the mods are removed, even if you think you did before this issue was posted, and let me know if the issue is gone.

**Comment by TarnishedCain** [comment]
Alright. I'll re-disable the mods and give it a full restart.

**Comment by TarnishedCain** [comment]
Yep. Still not working as intended. Here's the diag file.
[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/14590365/EpiphanyDiagnostics.tar.gz)

**Comment by TarnishedCain** [comment]
So, we got an idea of what's causing the issue? Mod conflicts? Missing file?

**Comment by OpenSauce04** [comment]
I will investigate the issue when I am able

**Comment by TarnishedCain** [comment]
SHOULDA KNEW YOU WERE COOKING WHEN YOU SAID YOU WERE BUSY 🔥🔥🔥🔥 TARNISHED LOST LOOKIN HELLA GREAT

**Comment by TarnishedCain** [comment]
Weird. This appears to happen with all active items, regardless of  which mod it is from.

**Comment by TarnishedCain** [comment]
FIXED: Was caused by a seperate mod (unsure which, but presumably Anathema/Vitiated Characters.)
